<article class="span-6 column">
    <div class="movieRow">
         <a href="/video/index/movie/id/<?php echo$this->id ?>">
            <img src="<?php echo '/Media/Videos/' . $this->poster ?>" alt="<?php echo $this->poster ?>" />
        </a>
        <p><a href="/video/index/movie/id/<?php echo $this->id ?>"> <?php echo $this->title ?></a><br />
            <?php echo $this->length($this->length) ?></p>
    </div>
</article>