<div class="offset3">
    <?php if ($this->paginator->count() > 1):?>
        <?php
        echo $this->paginationControl(
            $this->paginator, 'Sliding', '_paginatorControl.phtml'
        );
        ?>
    <?php endif?>
</div>

<table class="table table-striped table-condensed table-hover">
    <thead>
        <tr>
            <th>Cavs #</th>
            <th>Title</th>
            <th>Artist</th>
            <th>Publisher</th>
            <th>Disc Number</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $song):?>
            <?php echo $this->partial('_songRow.phtml', $song)?>
        <?php endforeach;?>
    </tbody>
</table>
<div class="offset3">
    <?php if ($this->paginator->count() > 1):?>
        <?php
        echo $this->paginationControl(
            $this->paginator, 'Sliding', '_paginatorControl.phtml'
        );
        ?>
    <?php endif?>
</div>