<section>
    <article>
        <?php foreach ($this->paginator as $album): ?>
            <?php $art = $this->artPath . $album->art ?>
            <img id="album_img" src="<?php echo $art ?>" alt="album art" height="300" width="300">
        </article>
        <div>
            <article>
                <table>
                    <thead>
                        <tr>
                            <th><?php echo $album->title ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Track #</th>
                            <th>Title</th>
                            <th>&nbsp;</th>
                        </tr>
                        <tr><td colspan="3"></td></tr>
                        <?php foreach ($album->getTracks() as $track): ?>
                            <tr>
                                <td><?php echo $track->track_number ?></td>
                                <td><?php echo $track->title ?></td>
                                <td><audio controls="controls" preload="none"><source src="<?php echo $this->path($track->path) ?>" type="audio/mp3" /></audio></td>
                            </tr>
                        </tbody>
                    <?php endforeach; ?>
                    <tfoot>
                        <tr>
                            <th colspan="3"><?php echo $album->artist->name ?></th>
                        </tr>
                    </tfoot>
                </table>
            <?php endforeach ?>
        </article>
    </div>
</section>
<?php echo $this->inlineScript() ?>
