<?php $art = $this->artPath . $this->album->art ?>
<section class="block">
    <article class="column span-4 prepend-8 append-12 last">
        <img id="album_img" src="<?php echo $art ?>" alt="album art" height="300" width="300">
    </article>
</section>
    <article class="table">
        <table>
            <thead>
                <tr>
                    <th colspan="3" class="large"><?php echo $this->album->name ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th class="tableth">Track #</th>
                    <th class="tableth">Title</th>
                    <th class="tableth">&nbsp;</th>
                </tr>
                <tr><td colspan="3"></td></tr>
                <?php foreach ($this->tracks as $track): ?>
                    <tr>
                        <td class="track"><?php echo $track->track ?></td>
                        <td class="title"><?php echo $track->title ?></td>
                        <td class="audio_player"><audio controls="controls" preload="none"><source src="<?php echo $this->path($track->path) ?>" type="audio/mp3" /></audio></td>
                    </tr>
                </tbody>
            <?php endforeach; ?>
            <tfoot>
                <tr>
                    <th colspan="3" class="alt large"><?php echo $this->album->artist->name ?></th>
                </tr>
            </tfoot>
        </table>
    </article>
<?php echo $this->inlineScript() ?>
