<div class="pagination"><?php
echo $this->paginationControl(
    $this->paginator, 'Sliding', '_paginatorControl.phtml'
)
?></div>
<section>
    <?php if ($this->paginator->getAdapter() instanceof Music_Model_Paginator_Album): ?>
        <?php foreach ($this->paginator as $album): ?>
            <?php $art = $this->artPath . $album->art ?>
            <img id="album_img" src="<?php echo $art ?>" alt="album art" height="300" width="300">
            <article>
                <table>
                    <thead>
                        <tr>
                            <th><a href="/music/index/album/id/<?php echo $album->id ?>"><?php echo $album->title ?></a></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Track #</th>
                            <th>Title</th>
                            <th>&nbsp;</th>
                        </tr>
                        <tr><td></td></tr>
                        <?php foreach ($album->getTracks() as $track): ?>
                            <?php if ($track->artist->id == $album->artist->id): ?>
                                <tr>
                                    <td><?php echo $track->getTrack() ?></td>
                                    <td><?php echo $track->getTitle() ?></td>
                                    <td><audio controls="controls" preload="none"><source src="<?php echo $this->path($track->path) ?>" type="audio/mp3" /></audio></td>
                                </tr>
                            <?php endif ?>
                        </tbody>
                    <?php endforeach; ?>
                    <tfoot>
                        <tr>
                            <th><?php echo $album->artist->name ?></th>
                        </tr>
                    </tfoot>
                </table>
            </article>
        <?php endforeach ?>
    <?php else: ?>
        <?php foreach ($this->paginator as $mp3): ?>
            <div>
                <article>
                    <table>
                        <thead>
                            <tr>
                                <th><?php echo $mp3->artist->name ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>Track #</th>
                                <th>Title</th>
                                <th>&nbsp;</th>
                            </tr>
                            <tr><td colspan="3"></td></tr>
                            <tr>
                                <td><?php echo $mp3->track_number ?></td>
                                <td><?php echo $mp3->title ?></td>
                                <td><audio controls="controls" preload="none"><source src="<?php echo $this->path($mp3->path) ?>" type="audio/mp3" /></audio></td>
                            </tr>
                        </tbody>
                    </table>
                </article>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</section>
<div class="pagination"><?php
    echo $this->paginationControl(
        $this->paginator, 'Sliding', '_paginatorControl.phtml'
    )
    ?></div>
<?php echo $this->inlineScript() ?>
