<div><?php
echo $this->paginationControl(
    $this->paginator, 'Sliding', '_paginatorControl.phtml'
)
?></div>
<section>
    <?php if ($this->paginator->getAdapter() instanceof Music_Model_Paginator_Album):?>
        <?php foreach ($this->paginator as $album):?>
            <?php $art = $this->artPath . $album->art?>
            <img id="album_img" src="<?php echo $art;?>" alt="album art" height="300" width="300">
            <article>
                <table class="table-bordered">
                    <thead>
                        <tr>
                            <th colspan="3"><a href="/music/index/album/id/<?php echo $album->id?>"><?php echo ucwords($album->title)?></a></th>
                        </tr>
                        <tr>
                            <th>Track #</th>
                            <th>Title</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tr><td></td></tr>
                    <?php foreach ($album->getTracks() as $track):?>
                        <?php if ($track->artist->id == $album->artist->id):?>
                                <!--                            <tbody>-->
                            <tr>
                                <td><?php echo $track->getTrack_number()?></td>
                                <td><?php echo $track->getTitle();?></td>
                                <td><a href="<?php echo $this->path($track->path . '/' . $track->getFilename())?>"><?php echo $track->getFilename()?></a></td>
                            </tr>
                            <!--                            </tbody>-->
                        <?php endif?>
                    <?php endforeach;?>
                    <tfoot>
                        <tr>
                            <th colspan="3"><?php echo ucwords($album->artist->name)?></th>
                        </tr>
                    </tfoot>
                </table>
            </article>
        <?php endforeach?>
    <?php else:?>
        <?php foreach ($this->paginator as $mp3):?>
            <article>
                <table class="table-bordered">
                    <thead>
                        <tr>
                            <th colspan="3"><?php echo ucwords($mp3->artist->name)?></th>
                        </tr>
                    </thead>
                    <!--<tbody>-->
                    <tr>
                        <th>Track #</th>
                        <th>Title</th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr><td colspan="3"></td></tr>
                    <tr>
                        <td><?php echo $mp3->track_number?></td>
                        <td><?php echo $mp3->title?></td>
                        <td><?php echo $this->path($mp3->path . '/' . $mp3->getFilename())?></td>
                    </tr>
                    <!--</tbody>-->
                </table>
            </article>
        <?php endforeach?>
    <?php endif?>
</section>
<div><?php
    echo $this->paginationControl(
        $this->paginator, 'Sliding', '_paginatorControl.phtml'
    )
    ?></div>
<?php echo $this->inlineScript()?>
