<div class="pagination"><?php
echo $this->paginationControl(
        $this->paginator, 'Sliding', '_paginatorControl.phtml'
)
?></div>
<article class="table">
    <?php
    $end_artist = '';
    $end_album = '';
    ?>
    <table>
        <?php
        foreach ($this->paginator as $track):;

            $artist = $track->getArtist()->name;
            $album = $track->getalbum()->title;
            ?>
            <?php if ($end_artist != $artist): ?>


                <thead>
                    <tr>
                        <th colspan="3"><?php echo $track->getArtist()->name ?></th>
                    </tr>
                </thead>
            <?php endif ?>
            <?php if ($end_album != $album): ?>

                <tr class="display">
                    <th><img src="<?php echo $this->artPath . 'thumbs/' . ucwords($track->getAlbum()->title) . '_thumb.jpg' ?>" alt="Album Art" /></th>
                    <th><a href="/music/index/album/id/<?php echo $track->getAlbum()->id ?>"><?php echo ucwords($track->getAlbum()->title) ?></a></th>
                    <th><?php echo $track->getAlbum()->year ?></th>
                </tr>

                <tr>
                    <th class="tableth">Track #</th>
                    <th class="tableth">Title</th>
                    <th class="tableth">&nbsp;</th>


                </tr>
            <?php endif; ?>
            <tr>
                <td class="track"><?php echo $this->escape($track->getTrack()) ?></td>
                <td class="title"><?php echo $this->escape($track->getTitle()) ?></td>
                <td class="audio_player"><audio controls="controls" preload="none">
                        <source src="<?php echo $this->path($track->getPath()) ?>" type="audio/mp3" /></audio></td>
            </tr>


            <?php
            $end_artist = $track->getArtist()->name;
            $end_album = $track->getAlbum()->title
            ?>

        <?php endforeach ?>
    </table>
</article>
<div class="pagination"><?php
        echo $this->paginationControl(
                $this->paginator, 'Sliding', '_paginatorControl.phtml'
        );
        ?>
</div>