<div class="pagination"><?php
echo $this->paginationControl(
        $this->paginator, 'Sliding', '_paginatorControl.phtml'
)
?></div>
<article class="table">
    <?php
    $end_artist = '';
    $end_album = '';
    ?>
    <table>
        <?php
        foreach ($this->paginator as $track):;
            $artist = $track->artist;
            $album = $track->album;
            ?>
            <?php if ($end_artist != $artist): ?>


                <thead>
                    <tr>
                        <th colspan="3"><?php echo $track->artist ?></th>
                    </tr>
                </thead>
            <?php endif ?>
            <?php if ($end_album != $album): ?>

                <tr class="display">
                    <th><img src="<?php echo $this->thumbPath . $track->album . '_thumb.jpg' ?>" alt="Album Art" /></th>
                    <th><a href="/music/index/album/id/<?php echo $track->album_id ?>"><?php echo $track->album ?></a></th>
                    <th><?php echo $track->year ?></th>
                </tr>

                <tr>
                    <th class="tableth">Track #</th>
                    <th class="tableth">Title</th>
                    <th class="tableth">&nbsp;</th>


                </tr>
            <?php endif; ?>
            <tr>
                <td class="track"><?php echo $track->track ?></td>
                <td class="title"><?php echo $track->title ?></td>
                <td class="audio_player"><audio controls="controls" preload="none"><source src="<?php echo $this->path($track->path) ?>" type="audio/mp3" /></audio></td>
            </tr>


            <?php
            $end_artist = $track->artist;
            $end_album = $track->album
            ?>

        <?php endforeach ?>
    </table>
</article>
<div class="pagination"><?php
        echo $this->paginationControl(
                $this->paginator, 'Sliding', '_paginatorControl.phtml'
        );
        ?>
</div>