<div><?php
echo $this->paginationControl(
    $this->paginator, 'Sliding', '_paginatorControl.phtml'
)
?>
</div>
<div class="row">
    <?php foreach ($this->paginator as $artist):?>
        <div class="span3">
            <table class="table-bordered">
                <tr>
                    <td class="button"><a href="/music/index/display/id/<?php echo $artist->id?>">
                            <?php echo ucwords($artist->name)?></a></td>
                </tr>
            </table>
        </div>
    <?php endforeach;?>
</div>
<div><?php
    echo $this->paginationControl(
        $this->paginator, 'Sliding', '_paginatorControl.phtml'
    )
    ?>
</div>
