<div class="pagination"><?php
echo $this->paginationControl(
    $this->paginator, 'Sliding', '_paginatorControl.phtml'
)
?>
</div>
<?php foreach ($this->paginator as $artist): ?>
    <table class="genre">
        <tr>
            <td><a href="/music/index/display/id/<?php echo $artist->id ?>">
                    <?php echo $artist->name ?></a></td>
        </tr>
    </table>
<?php endforeach; ?>
<div class="pagination"><?php
echo $this->paginationControl(
    $this->paginator, 'Sliding', '_paginatorControl.phtml'
)
?>
</div>
