<article class="search">
    <form action="<?php echo $this->element->getAction()?>"
          method="<?php echo $this->element->getMethod()?>">
        <table>
            <tr>
                <th><?php echo $this->element->query->renderLabel()?></th>
            </tr>
            <tr>
                <td><?php echo $this->element->query->renderViewHelper()?></td>
            </tr>
            <tr>
                <td><?php echo $this->element->search?></td>
            </tr>
        </table>
    </form>
</article>