<tr>
    <td><input type="hidden" name="id" value="<?php echo $this->id ?>" /><?php echo $this->id ?></td>
    <td><input type="text" name="name" size="40" value="<?php echo $this->name ?>" /></td>
    <td><input type="text" name="name" size="40" value="<?php echo $this->year ?>" /></td>
    <td><input type="text" name="name" size="40" value="<?php echo $this->art ?>" /></td>
    <td><a href='/admin/music/updatealbum/id/<?php echo $this->id ?>'>Edit</a></td>
</tr>