<tr>
    <td><input type="hidden" name="id" value="<?php echo $this->id ?>" /><?php echo $this->id ?></td>
    <td><input type="text" name="name" size="40" value="<?php echo $this->name ?>" /></td>
    <td><a href='/admin/music/updateartist/id/<?php echo $this->id ?>'>Edit</a></td>
</tr>

<div class="column span-10 prepend-2">
    <table>
        <?php //echo $this->partialLoop('_album.phtml', $this->getAlbums()) ?>
    </table>
</div>