<article>
    <form action="<?php echo $this->element->getAction()?>"
          method="<?php echo $this->element->getMethod()?>">
        <table>
            <tr>
                <th colspan="2">Update Artist: <?php echo $this->element->name->getValue()?></th>
            </tr>
            <tr>
                <td><?php echo $this->element->name->renderLabel()?></td>
                <td><?php echo $this->element->name->renderViewHelper()?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->element->submit?></td>
            </tr>
            <tr>
                <td colspan="2"><a href="/admin/music/delete/artistId/<?php echo $this->element->id->getValue()?>" >Delete this artist!</a></td>
            </tr>
        </table>
        <?php echo $this->element->id?>
    </form>
</article>