<article>
    <form action="<?php echo $this->element->getAction() ?>"
          method="<?php echo $this->element->getMethod() ?>">
        <table>
            <tr>
                <th colspan="2">Update Track: <?php echo $this->element->title->getValue() ?></th>
            </tr>
            <tr>
                <td><?php echo $this->element->title->renderLabel() ?></td>
                <td><?php echo $this->element->title->renderViewHelper() ?></td>
            </tr>
            <tr>
                <td><?php echo $this->element->genre->renderLabel() ?></td>
                <td><?php echo $this->element->genre->renderViewHelper() ?></td>
            </tr>
            <tr>
                <td><?php echo $this->element->path->renderLabel() ?></td>
                <td><?php echo $this->element->path->renderViewHelper() ?></td>
            </tr>
            <tr>
                <td><?php echo $this->element->filename->renderLabel() ?></td>
                <td><?php echo $this->element->filename->renderViewHelper() ?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->element->submit ?></td>
            </tr>
            <tr>
                <td colspan="2"><a href="/admin/music/delete/trackId/<?php echo $this->element->id->getValue() ?>" >Delete this track</a></td>
            </tr>
        </table>
        <?php echo $this->element->id ?>
        <?php echo $this->element->artist ?>
        <?php echo $this->element->album ?>
        <?php echo $this->element->format ?>
        <?php echo $this->element->hash ?>
        <?php echo $this->element->playtime ?>
        <?php echo $this->element->track_number ?>
    </form>
</article>