<?php echo $this->doctype() . "\n" ?>
<html>
    <head>
        <?php echo $this->headTitle() . "\n"; ?>
        <?php echo $this->headMeta() . "\n"; ?>
        <?php echo $this->headLink() . "\n" ?>
        <?php echo $this->headscript() . "\n" ?>

        <!--[if IE]><script type="text/javascript" src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    </head>
    <body>
        <section class="container">
            <header class="block">
                <div id="header">
                    <div class="column span-18">
                        <h1>HOME</h1>
                    </div>
                    <div id="login" class="column span-6 last">
                        <?php echo $this->layout()->login . "\n" ?>
                    </div>
                </div>
                <nav>
                    <div id="nav" class="column span-24">
                        <a href="/">Home</a>
                        <a href="/music/index">Music</a>
                        <a href="/video/index">Videos</a>
                        <a href="/admin/index">Admin</a>
                        <a href="/karaoke/index">Karaoke</a>
                        <?php echo $this->layout()->nav ?>&nbsp;
                    </div>
                </nav>
            </header>
            <section class="block">
                <div id="main" class="column span-18 border">
                    <div id="flash">
                        <?php
                        if (count($this->messages) > 0) {
                            printf("<h3 id='flash'>%s</h3>", $this->messages[0]);
                        }
                        ?>
                    </div>
                    <?php echo $this->layout()->content; ?>

                </div>
                <aside id="sidebar" class="column span-4 last">
                    <?php echo $this->layout()->search ?>
                    <div id="subNav">
                        <?php echo $this->layout()->subNav ?>&nbsp;
                    </div>
                    <div id="adminMenu">
                        <h4>Administration Links</h4>
                        <a href="/admin/music/read">Scan Music Files</a><br />
                        <a href="/admin/moviexml/index">Movie Xml</a><br />
                        <a href="/admin/music/update">Update Music Info</a>
                        <?php echo $this->layout()->adminMenu ?>&nbsp;
                    </div>
                </aside>
            </section>
            <footer class="block">
                <div id="footer" class="column span-24">
                    <p>Created by <em>John Schoenwolf</em> with <a href="http://framework.zend.com/">Zend Framework. &COPY; </a></p>
                    <!--  TODO remove following line for production enviroment  -->
                    <?php
                    $this->addScriptPath(APPLICATION_PATH . '/views/scripts');
                    echo $this->render('profiler.phtml')
                    ?>
                </div>
            </footer>
        </section>
    </body>
</html>
<?php echo $this->inlineScript() ?>


