<?php echo $this->doctype() . "\n" ?>
<html>
    <head>
        <?php echo $this->headTitle() . "\n" ?>
        <?php echo $this->headMeta() . "\n" ?>
        <?php echo $this->headLink() . "\n" ?>
        <?php echo $this->headscript() . "\n" ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="span12">
                    <header>
                        <div class="row">
                            <div class="span8">
                                <h1>HOME</h1>
                            </div>
                            <div id="login" class="span4">
                                <?php echo $this->layout()->login . "\n" ?>
                            </div>
                        </div>
                        <nav class="row">
                            <div class="span12">
                                <div id="nav" class="navbar">
                                    <a href="/">Home</a>
                                    <a href="/music/index">Music</a>
                                    <a href="/video/index">Videos</a>
                                    <a href="/admin/index">Admin</a>
                                    <a href="/karaoke/index">Karaoke</a>
                                    <?php echo $this->layout()->nav ?>&nbsp;
                                </div>
                            </div>
                        </nav>
                    </header>
                </div>
            </div>
        </div>
        <section class="container">
            <article class="row">
                <div id="main" class="span12">
                    <div class="row">
                        <div class="span9">
                            <div id="flash">
                                <?php
                                if (count($this->messages) > 0) {
                                    printf("<h3 id='flash'>%s</h3>", $this->messages[0]);
                                }
                                ?>
                            </div>
                            <div id="content">
                                <?php echo $this->layout()->content; ?>
                            </div>
                        </div>
                        <aside class="span3">
                            <div>
                                <?php echo $this->layout()->search ?>
                            </div>
                            <div id="subNav">
                                <?php echo $this->layout()->subNav ?>&nbsp;
                            </div>
                            <div class="sidebar-nav">
                                <div id="adminMenu">
                                    <h4>Administration Links</h4>
                                    <a href="/admin/music/read">Scan Music Files</a><br />
                                    <a href="/admin/moviexml/index">Movie Xml</a><br />
                                    <a href="/admin/music/update">Update Music Info</a>
                                    <?php echo $this->layout()->adminMenu ?>&nbsp;
                                </div>
                            </div>
                        </aside>
                    </div>
                </div>
            </article>
            <div class="row">
                <div class="span12">
                    <footer>
                        <p>Created by <em>John Schoenwolf</em> with <a href="http://framework.zend.com/">Zend Framework</a> and <a href="http://twitter.github.com/bootstrap">Twitter Bootstrap</a> &COPY;</p>
                        <!--  TODO remove following line for production enviroment  -->
                        <?php
                        $this->addScriptPath(APPLICATION_PATH . '/views/scripts');
                        echo $this->render('profiler.phtml')
                        ?>
                    </footer>
                </div>
            </div>
        </section>
    </body>
</html>
<?php echo $this->inlineScript() ?>


