<?php echo $this->doctype() . "\n"?>
<html>
    <head>
        <?php echo $this->headTitle() . "\n"?>
        <?php echo $this->headMeta() . "\n"?>
        <?php echo $this->headLink() . "\n"?>
        <?php echo $this->headscript() . "\n"?>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span12">
                    <header>
                        <div class="row-fluid">
                            <div class="span8">
                                <h1>Hi</h1>
                            </div>
                        </div>
                        <nav class="row-fluid">
                            <div class="span12">
                                <div id="nav">
                                    <a href="/karaoke/index">By ID</a>
                                    <a href="/karaoke/index/artist">By Artist</a>
                                    <a href="/karaoke/index/search">Search</a>
                                    <?php echo $this->layout()->nav?>&nbsp;
                                </div>
                            </div>
                        </nav>
                    </header>
                </div>
            </div>
        </div>
        <section class="container-fluid">
            <article class="row-fluid">
                <div class="span12">
                    <div class="row-fluid">
<!--                        <div class="span9">-->
                            <div id="flash">
                                <?php
                                if (count($this->messages) > 0) {
                                    printf("<h3 id='flash'>%s</h3>", $this->messages[0]);
                                }
                                ?>
                            </div>
                            <div>
                                <?php echo $this->layout()->content;?>
                            </div>
<!--                        </div>-->
                        
                    </div>
                </div>
            </article>
            <div class="row-fluid">
                <div class="span12">
                    <footer>
                        <p>Created by <em>John Schoenwolf</em> with <a href="http://framework.zend.com/">Zend Framework</a> and <a href="http://twitter.github.com/bootstrap">Twitter Bootstrap</a> &COPY;</p>
                        <!--  TODO remove following line for production environment  -->
                        <?php
                        $this->addScriptPath(APPLICATION_PATH . '/views/scripts');
                        echo $this->render('profiler.phtml')
                        ?>
                    </footer>
                </div>
            </div>
        </section>
    </body>
</html>
<?php echo $this->inlineScript()?>


