<article class="alpha_table">
    <h2>Browse Music Collection</h2>
    <table class="alpha">
        <tr>
            <td>
                <a  href="/music/search/index/query/a">A</a>
            </td>
            <td>
                <a  href="/music/search/index/query/b">B</a>
            </td>
            <td>
                <a  href="/music/search/index/query/c">C</a>
            </td>
            <td>
                <a  href="/music/search/index/query/d">D</a>
            </td>
            <td>
                <a  href="/music/search/index/query/e">E</a>
            </td>
        </tr>
        <tr>
            <td>
                <a  href="/music/search/index/query/f">F</a>
            </td>
            <td>
                <a  href="/music/search/index/query/g">G</a>
            </td>
            <td>
                <a  href="/music/search/index/query/h">H</a>
            </td>
            <td>
                <a  href="/music/search/index/query/i">I</a>
            </td>
            <td>
                <a  href="/music/search/index/query/j">J</a>
            </td>
        </tr>
        <tr>
            <td>
                <a  href="/music/search/query/k">K</a>
            </td>
            <td>
                <a  href="/music/search/index/query/l">L</a>
            </td>
            <td>
                <a  href="/music/search/index/query/m">M</a>
            </td>
            <td>
                <a  href="/music/search/index/query/n">N</a>
            </td>
            <td>
                <a  href="/music/search/index/query/o">O</a>
            </td>
        </tr>
        <tr>
            <td>
                <a  href="/music/search/index/query/p">P</a>
            </td>
            <td>
                <a  href="/music/search/index/query/q">Q</a>
            </td>
            <td>
                <a  href="/music/search/index/query/r">R</a>
            </td>
            <td>
                <a  href="/music/search/index/query/s">S</a>
            </td>
            <td>
                <a  href="/music/search/index/query/t">T</a>
            </td>
        </tr>
        <tr>
            <td>
                <a  href="/music/search/index/query/u">U</a>
            </td>
            <td>
                <a  href="/music/search/index/query/v">V</a>
            </td>
            <td>
                <a  href="/music/search/index/query/w">W</a>
            </td>
            <td>
                <a  href="/music/search/index/query/x">X</a>
            </td>
            <td>
                <a  href="/music/search/index/query/y">Y</a>
            </td>
        </tr>
        <tr>
            <td>
                <a  href="/music/search/index/query/z">Z</a>
            </td>
            <td id="gap" colspan="4">

            </td>
        </tr>
        <tr>
            <td>
                <a  href="/music/search/index/query/0">0</a>
            </td>
            <td>
                <a  href="/music/search/index/query/1">1</a>
            </td>
            <td>
                <a  href="/music/search/index/query/2">2</a>
            </td>
            <td>
                <a  href="/music/search/index/query/3">3</a>
            </td>
            <td>
                <a  href="/music/search/index/query/4">4</a>
            </td>
        </tr>
        <tr>
            <td>
                <a  href="/music/search/index/query/5">5</a>
            </td>
            <td>
                <a  href="/music/search/index/query/6">6</a>
            </td>
            <td>
                <a  href="/music/search/index/query/7">7</a>
            </td>
            <td>
                <a  href="/music/search/index/query/8">8</a>
            </td>
            <td>
                <a  href="/music/search/index/query/9">9</a>
            </td>
        </tr>
    </table>
</article>