<div class="column span-16 prepend-4">
    <form action="/admin/music/updateartist" method="POST" id="artistUpdate">
        <table class="edit">
            <tr>
                <th><input type="text" size="30" name="name" value="<?php echo $this->artists->name ?>" /></th>
                <th><a href="/admin/music/updateartist/id/<?php echo $this->artists->id ?>">Edit Artist</a></th>
            </tr>
            <tr>
                <th colspan="2">Albums</th>
            </tr>
            <?php foreach ($this->artists->getAlbums() as $album): ?>
                <tr>
                <table class="edit">
                    <tr>
                        <th colspan="4"><?php echo $album->name ?></th>
                        <td><a href="/admin/music/updatealbum/id/<?php echo $album->id ?>">Edit Album</a></td>
                    </tr>
                    <tr>
                        <td colspan="4"><img src="<?php echo $this->thumbPath . $album->name . '_thumb.jpg' ?>" alt="thumbnail"/></td>
                        <td><?php echo $album->year ?></td>
                    </tr>


                        <?php foreach ($album->getTracks() as $track): ?>
                            <tr>
                                <td><input type="text" name="track" size="2" value="<?php echo $track->track ?>" /></td>
                                <td><input type="text" name="title" size="35" value="<?php echo $track->title ?>" /></td>
                                <td><input type="text" name="genre" size="8" value="<?php echo $track->genre ?>" /></td>
                                <td><?php echo $this->Playtime($track->play_time) ?></td>
                                <td><a href="/admin/music/updatetrack/id/<?php echo $track->id ?>">Edit Track</a></td>

                            </tr>
                        <?php endforeach ?>


                </table>
                </tr>
            <?php endforeach ?>
        </table>
    </form>
</div>