<?php
$session = new Zend_Session_Namespace('page');
$page = $this->paginator->getCurrentPageNumber();
?>
<div class="pagination">
    <?php
    echo $this->paginationControl(
        $this->paginator, 'Sliding', '_paginatorControl.phtml'
    )
    ?>
</div>
<article>
    <?php foreach ($this->paginator as $artist): ?>
        <table>
            <tr>
                <th colspan="4"><?php echo $artist->name ?></th>
                <th><a href="/admin/music/updateartist/id/
                       <?php echo $this->escape($artist->id) ?>">Edit Artist</a></th>
            </tr>
            <?php if (count($artist->getAlbums()) > 0): ?>
                <tr>
                    <th colspan="5">Albums</th>
                </tr>
                <?php foreach ($artist->getAlbums() as $album): ?>

                    <tr>
                        <th colspan="4"><?php echo $this->escape($album->title) ?></th>
                        <td><a href="/admin/music/updatealbum/id/
                               <?php echo $this->escape($album->id) ?>">Edit Album</a></td>
                    </tr>
                    <tr>
                        <td colspan="4"><img src="<?php
                   echo $this->thumbPath .
                   $this->escape($album->title) . '_thumb.jpg'
                               ?>"
                                             alt="thumbnail"/></td>
                        <td><?php echo $this->escape($album->year) ?></td>
                    </tr>

                    <?php foreach ($album->getTracks() as $track): ?>
                        <tr>
                            <td><?php echo $this->escape($track->track_number) ?></td>
                            <td><?php echo $this->escape($track->title) ?></td>
                            <td><?php echo $this->escape($track->genre) ?></td>
                            <td><?php echo $this->escape($this->Playtime($track->playtime)) ?></td>
                            <td><a href="<?php
                echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'music',
                    'action' => 'updatetrack',
                    'id' => $track->id));
                $session->page = $page;
                        ?>">Edit Track</a></td>
                        </tr>
                    <?php endforeach ?>
                <?php endforeach ?>
            <?php else: ?>
                <tr>
                    <th colspan="5">Tracks</th>
                </tr>
                <?php foreach ($artist->getTracks() as $track): ?>
                    <tr>
                        <td><?php echo $this->escape($track->track_number) ?></td>
                        <td><?php echo $this->escape($track->title) ?></td>
                        <td><?php echo $this->escape($track->genre) ?></td>
                        <td><?php echo $this->escape($this->Playtime($track->playtime)) ?></td>
                        <td><a href="<?php
            echo $this->url(array(
                'module' => 'admin',
                'controller' => 'music',
                'action' => 'updatetrack',
                'id' => $this->escape($track->id)));
            $session->page = $page;
                    ?>">Edit Track</a></td>
                    </tr>
                <?php endforeach ?>
            <?php endif ?>
        </table>
    <?php endforeach; ?>
</article>
<div class="pagination">
    <?php
    echo $this->paginationControl(
        $this->paginator, 'Sliding', '_paginatorControl.phtml'
    )
    ?>
</div>
